### ISSUE TITLE
Impossible to download the converted file

### ISSUE THREAD

**Issue by zarevskaya** [Arthur2500/ConvertZ#4]
Hi,

I tried your application, I encounter a problem when I want to download the converted file.

![Screenshot_20240820_132557](https://github.com/user-attachments/assets/40767900-c55e-43fa-99e4-749be39eaa77)

Any hint?

**Comment by Arthur2500** [comment]
im working on a large refactoring, please stand by

**Comment by zarevskaya** [comment]
Ok, thank you.
